### ISSUE TITLE
Need to differentiate attack names for multiattack monsters

### ISSUE THREAD

**Issue by michaelmannello** [Obsidian-TTRPG-Community/Pathfinder-2E-SRD-Markdown#8]
Any field in JSON with an identical Name to ones above it will overwrite that field, not create an additional. So an adult cloud dragon, for instance, has 4 melee attacks: jaws, claw, tail, and horn. But because all of these attacks are named "Melee," only the horn will show when the statblock renders. The attacks need to be given unique names. At least this is what I'm thinking; if I'm doing something wrong please lmk!

**Comment by sigrunixia** [comment]
This is a known bug in Fantasy Statblocks, that is in the process of getting fixed, that is causing this behaviour. For the interim, the fix is to slightly adjust the description as you need to use the entity. 

Because this is the common way entities are formatted in Pathfinder, we're waiting for the plugin fix instead of changing the source files.

**Comment by miscoined** [comment]
Hey! Was just wondering if there was an existing bug for this in fantasy statblocks that I could watch? At the moment I'm manually differentiating my blocks with 'melee (horn)' etc, but it'd be good to know when I can stop doing that. I saw this issue (https://github.com/javalent/fantasy-statblocks/issues/228) but that appears to be related to the description, not the name.

**Comment by sigrunixia** [comment]
> Hey! Was just wondering if there was an existing bug for this in fantasy statblocks that I could watch? At the moment I'm manually differentiating my blocks with 'melee (horn)' etc, but it'd be good to know when I can stop doing that. I saw this issue ([javalent/fantasy-statblocks#228](https://github.com/javalent/fantasy-statblocks/issues/228)) but that appears to be related to the description, not the name.

If you can see this milestone, you can watch it as well. The same bug that affects descriptions also affects names. 
https://github.com/javalent/fantasy-statblocks/milestone/1

It started up after https://github.com/javalent/fantasy-statblocks/issues/222. And created https://github.com/javalent/fantasy-statblocks/issues/224. 

Fixing this without a complete rework breaks `extends` so.. after Calendarium is caught up on some things, this is next. :)
